import Head from 'next/head'
import React from 'react'
import Breadcrumb from '../components/layouts/Toolbar/Breadcrumb'
import Toolbar from '../components/layouts/Toolbar/Index'
import PageAction from '../components/layouts/Toolbar/PageAction'
import PageTitle from '../components/layouts/Toolbar/PageTitle'

import { motion } from 'framer-motion'

function about() {
  return (
    <>
    <Head>
      <title>About</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

          {/* Toolbar */}
          <Toolbar>
            <PageTitle> 
              <h1 className='page-title'> About </h1>
              <Breadcrumb/>
            </PageTitle>
            <PageAction>
              Action
            </PageAction>
          </Toolbar>

          {/* Container */}
          <div className='flex flex-grow flex-shrink-0'> 
            <div className='w-full lg:py-0 lg:px-[30px] m-auto container-fluid '> 
              <div className='bg-white py-5 px-9 rounded-lg'> 
                about page
              </div>
            </div>
          </div>
    </>
  )
}

export default about