import Head from 'next/head'
import React from 'react'

function about() {
  return (
    <>
    <Head>
      <title>About</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

     {/* Toolbar */}
        <div className='flex items-center w-full justify-between mb-5'> Toolbar </div>
        
        {/* Container */}
        <div> About </div>
    </>
  )
}

export default about